name: jax-alpr
channels:
  - conda-forge
  - nvidia
dependencies:
  - python=3.9
  - pip=23.1.2
  - jaxlib=0.4.7=*cuda*
  - jax=0.4.8
  - cudatoolkit=11.7
  - cuda-nvcc=11.7
  - cudnn
  - opencv
  - jupyter
  - pip:
    - flax
    - optax
    - ml_collections
